name = "dinosoup"
version = "0.0.2"

description = "Dynamic Supervisor for Erlang/OTP written in Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "kodumbeats", repo = "dinosoup" }
links = [{ title = "author", href = "https://kdmb.ca" }]

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
gleam_otp = "~> 0.9"
gleam_erlang = "~> 0.24"

[dev-dependencies]
gleeunit = "~> 1.0"
